name: Semgrep Code Scan

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    name: Code Scan
    runs-on: ${{ vars.RUNNER_LINUX }}
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - run: semgrep scan --config auto
